version: '3.8'

services:
  em-processor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://em-discovery:8761/eureka/
    depends_on:
      - redis
      - em-discovery

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  em-discovery:
    build:
      context: ../em-discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761